-- clauses obligatoires :
SELECT      NOM_COLONNE_1 [, NOM_COLONNE_2, ..., NOM_COLONNE_n]
FROM        NOM_TABLE_1
-- clauses optionnelles (selon besoins)
JOIN        NOM_TABLE_2 ON NOM_TABLE_1.CLE_PRIMAIRE = NOM_COLONNE_2.CLE_ETRANGERE
WHERE       < CONDITIONS_FILTRE >
GROUP BY    < NOM_COLONNE_REGROUPEMENT_1 [, NOM_COLONNE_REGROUPEMENT_2, ...] >
HAVING      < CONDITIONS_FILTRE_POUR_FONCTIONS_AGREGEES >
ORDER BY    NOM_COLONNE_TRI_1 [, NOM_COLONNE_TRI_2, ...]
LIMIT       < NOMBRE_ENREGISTREMENTS >



--autre exemple
